// <auto-generated />
using System;
using GestorDeVuelosProyectoFinal.src.Shared.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestorDeVuelosProyectoFinal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416144004_PassengerTypes")]
    partial class PassengerTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AirlinesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<Guid?>("CountriesEntityId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Country_Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("country_id");

                    b.Property<DateTime?>("Created_In")
                        .HasColumnType("date")
                        .HasColumnName("created_in");

                    b.Property<string>("Iata_Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("iata_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Name");

                    b.Property<DateTime?>("Updated_On")
                        .HasColumnType("date")
                        .HasColumnName("updated_on");

                    b.HasKey("Id");

                    b.HasIndex("CountriesEntityId");

                    b.HasIndex("Country_Id");

                    b.HasIndex("Iata_Code")
                        .IsUnique();

                    b.ToTable("airlines", (string)null);
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Addresses.Infrastructure.Entity.AddressesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid?>("CitiesEntityId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Cities_id")
                        .HasColumnType("char(36)")
                        .HasColumnName("city_id");

                    b.Property<string>("Complement")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("complement");

                    b.Property<string>("Number")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("number");

                    b.Property<string>("PathName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("path_name");

                    b.Property<string>("Postal_code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("postal_code");

                    b.Property<Guid>("ViaType_id")
                        .HasColumnType("char(36)")
                        .HasColumnName("viatype_id");

                    b.Property<Guid?>("ViaTypesEntityId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CitiesEntityId");

                    b.HasIndex("Cities_id");

                    b.HasIndex("ViaType_id");

                    b.HasIndex("ViaTypesEntityId");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.AirPorts.Infrastructure.Entity.AirPortsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid?>("CitiesEntityId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Cities_Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("cities_id");

                    b.Property<string>("Iata_Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("iata_code");

                    b.Property<string>("Icao_Code")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("icao_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CitiesEntityId");

                    b.HasIndex("Cities_Id");

                    b.HasIndex("Iata_Code")
                        .IsUnique();

                    b.HasIndex("Icao_Code")
                        .IsUnique();

                    b.ToTable("airports", (string)null);
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Aircraft.Infrastructure.Entity.AircraftEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<Guid?>("AircraftModelsEntityId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Airline_Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("airline_Id");

                    b.Property<Guid?>("AirlinesEntityId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("Manufacturing_date")
                        .HasColumnType("date")
                        .HasColumnName("manufacturing_date");

                    b.Property<Guid>("Models_Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("models_Id");

                    b.Property<string>("Tuition")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tuition");

                    b.HasKey("Id");

                    b.HasIndex("AircraftModelsEntityId");

                    b.HasIndex("Airline_Id");

                    b.HasIndex("AirlinesEntityId");

                    b.HasIndex("Models_Id");

                    b.HasIndex("Tuition")
                        .IsUnique();

                    b.ToTable("Aircraft", (string)null);
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.AircraftManufacturers.Infrastructure.Entity.AircraftManufacturersEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("country");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("aircraft_manufacturers", (string)null);
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.AircraftModels.Infrastructure.Entity.AircraftModelsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid?>("AircraftManufacturersEntityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Cruise_Speed_kmh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cruise_speed_kmh");

                    b.Property<string>("Cruising_Altitude_ft")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cruising_altitude_ft");

                    b.Property<decimal?>("Fuel_Consumption_kg_h")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("fuel_consumption_kg_h");

                    b.Property<Guid>("Manufacturer_id")
                        .HasColumnType("char(36)")
                        .HasColumnName("manufacturer_id");

                    b.Property<string>("Maximum_Capacity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("maximum_capacity");

                    b.Property<decimal?>("Maximum_Takeoff_Weight_kg")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("maximum_takeoff_weight_kg");

                    b.Property<string>("Model_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("model_name");

                    b.HasKey("Id");

                    b.HasIndex("AircraftManufacturersEntityId");

                    b.HasIndex("Manufacturer_id");

                    b.ToTable("aircraft_models", (string)null);
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.AirportAirline.Infrastructure.Entity.AirportAirlineEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<Guid?>("AirPortsEntityId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Airline_Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("airline_Id");

                    b.Property<Guid?>("AirlinesEntityId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Airport_Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("airport_Id");

                    b.Property<DateTime?>("End_Date")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<DateTime?>("Start_Date")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Terminal")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("terminal");

                    b.HasKey("Id");

                    b.HasIndex("AirPortsEntityId");

                    b.HasIndex("Airline_Id")
                        .IsUnique();

                    b.HasIndex("AirlinesEntityId");

                    b.HasIndex("Airport_Id")
                        .IsUnique();

                    b.ToTable("AirportAirline", (string)null);
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.AvailabilityStates.Infrastructure.Entity.AvailabilityStatesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("availability_states", (string)null);
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.CabinConfiguration.Infrastructure.Entity.CabinConfigurationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid?>("AircraftEntityId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Aircraft_id")
                        .HasColumnType("char(36)")
                        .HasColumnName("aircraft_id");

                    b.Property<Guid>("Cabin_Type_Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("cabin_Type_Id");

                    b.Property<int>("End_Row")
                        .HasColumnType("int")
                        .HasColumnName("end_row");

                    b.Property<string>("Seat_letters")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("seat_letters");

                    b.Property<int>("Seats_per_row")
                        .HasColumnType("int")
                        .HasColumnName("seats_per_row");

                    b.Property<int>("Start_Row")
                        .HasColumnType("int")
                        .HasColumnName("start_row");

                    b.HasKey("Id");

                    b.HasIndex("AircraftEntityId");

                    b.HasIndex("Aircraft_id");

                    b.HasIndex("Cabin_Type_Id");

                    b.ToTable("cabin_configuration", (string)null);
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.CabinTypes.Infrastructure.Entity.CabinTypesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("cabin_types", (string)null);
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Cities.Infrastructure.Entity.CitiesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<Guid>("Regions_id")
                        .HasColumnType("char(36)")
                        .HasColumnName("regions_id");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Regions_id");

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Continents.Infrastructure.Entity.ContinentsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Continents", (string)null);
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Countries.Infrastructure.Entity.CountriesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("Continents_id")
                        .HasColumnType("char(36)")
                        .HasColumnName("continente_id");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("iso_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Continents_id");

                    b.HasIndex("IsoCode")
                        .IsUnique();

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Customers.Infrastructure.Entity.CustomersEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Created_in")
                        .HasColumnType("datetime")
                        .HasColumnName("created_in");

                    b.Property<Guid>("People_Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("people_Id");

                    b.HasKey("Id");

                    b.HasIndex("People_Id")
                        .IsUnique();

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.DocumentTypes.Infrastructure.Entity.DocumentTypesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("document_types", (string)null);
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.EmailDomains.Infrastructure.Entity.EmailDomainsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Domains")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("domains");

                    b.HasKey("Id");

                    b.HasIndex("Domains")
                        .IsUnique();

                    b.ToTable("email_domains", (string)null);
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.FlightStatus.Infrastructure.Entity.FlightStatusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("flight_status", (string)null);
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.FlightStatusTransitions.Infrastructure.Entity.FlightStatusTransitionsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("Destination_State_Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("destination_state_id");

                    b.Property<Guid?>("FlightStatusEntityId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Origin_State_Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("origin_state_id");

                    b.HasKey("Id");

                    b.HasIndex("Destination_State_Id");

                    b.HasIndex("FlightStatusEntityId");

                    b.HasIndex("Origin_State_Id", "Destination_State_Id")
                        .IsUnique();

                    b.ToTable("flight_status_transitions", null, t =>
                        {
                            t.HasCheckConstraint("CK_FlightStatusTransitions_NoSelf", "origin_state_id <> destination_state_id");
                        });
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Flights.Infrastructure.Entity.FlightsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid?>("AircraftEntityId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AircraftId")
                        .HasColumnType("char(36)")
                        .HasColumnName("aircraft_id");

                    b.Property<Guid>("AirlineId")
                        .HasColumnType("char(36)")
                        .HasColumnName("airline_id");

                    b.Property<Guid?>("AirlinesEntityId")
                        .HasColumnType("char(36)");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int")
                        .HasColumnName("available_seats");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime")
                        .HasColumnName("departure_date");

                    b.Property<DateTime>("EstimatedArrivalDate")
                        .HasColumnType("datetime")
                        .HasColumnName("estimated_arrival_date");

                    b.Property<string>("FlightCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("flight_code");

                    b.Property<Guid>("FlightStateId")
                        .HasColumnType("char(36)")
                        .HasColumnName("flight_state_id");

                    b.Property<Guid?>("FlightStatusEntityId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("RescheduledAt")
                        .HasColumnType("datetime")
                        .HasColumnName("rescheduled_at");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("char(36)")
                        .HasColumnName("route_id");

                    b.Property<int>("TotalCapacity")
                        .HasColumnType("int")
                        .HasColumnName("total_capacity");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("UpdatedAt"));

                    b.HasKey("Id");

                    b.HasIndex("AircraftEntityId");

                    b.HasIndex("AircraftId");

                    b.HasIndex("AirlineId");

                    b.HasIndex("AirlinesEntityId");

                    b.HasIndex("FlightCode")
                        .IsUnique();

                    b.HasIndex("FlightStateId");

                    b.HasIndex("FlightStatusEntityId");

                    b.HasIndex("RouteId");

                    b.ToTable("flights", null, t =>
                        {
                            t.HasCheckConstraint("CK_Flights_AvailableSeats", "available_seats >= 0");

                            t.HasCheckConstraint("CK_Flights_Capacity", "total_capacity > 0");

                            t.HasCheckConstraint("CK_Flights_Dates", "estimated_arrival_date > departure_date");

                            t.HasCheckConstraint("CK_Flights_Seats", "available_seats <= total_capacity");
                        });
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.PassengerTypes.Infrastructure.Entity.PassengerTypesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int?>("Max_Age")
                        .HasColumnType("int")
                        .HasColumnName("max_age");

                    b.Property<int?>("Min_Age")
                        .HasColumnType("int")
                        .HasColumnName("min_age");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("passenger_types", null, t =>
                        {
                            t.HasCheckConstraint("CK_PassengerTypes_AgeRange", "max_age IS NULL OR min_age IS NULL OR max_age >= min_age");
                        });
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.People.Infrastructure.Entity.PeopleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("Addresses_Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("address_id");

                    b.Property<DateTime?>("Created_in")
                        .HasColumnType("datetime")
                        .HasColumnName("created_in");

                    b.Property<DateTime?>("DateBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_birth");

                    b.Property<Guid>("DocumentTypes_Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("documenttype_id");

                    b.Property<string>("Document_Number")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("document_number");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Surnames")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("surnames");

                    b.Property<DateTime?>("updated_in")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_in");

                    b.HasKey("Id");

                    b.HasIndex("Addresses_Id");

                    b.HasIndex("DocumentTypes_Id");

                    b.HasIndex("Document_Number")
                        .IsUnique();

                    b.ToTable("people", (string)null);
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.PeopleEmails.Infrastructure.Entity.PeopleEmailsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("Domain_Email_Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("domain_email_id");

                    b.Property<Guid?>("EmailDomainsEntityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email_User")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email_user");

                    b.Property<bool>("EsPrincipal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("es_principal");

                    b.Property<Guid?>("PeopleEntityId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("People_Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("people_id");

                    b.HasKey("Id");

                    b.HasIndex("Domain_Email_Id");

                    b.HasIndex("EmailDomainsEntityId");

                    b.HasIndex("PeopleEntityId");

                    b.HasIndex("People_Id");

                    b.ToTable("people_emails", (string)null);
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.PeoplePhones.Infrastructure.Entity.PeoplePhonesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<bool>("Is_main")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_main");

                    b.Property<Guid?>("PeopleEntityId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("People_Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("people_Id");

                    b.Property<Guid>("PhoneCode_Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("phonecode_Id");

                    b.Property<string>("Phone_number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.HasIndex("PeopleEntityId");

                    b.HasIndex("People_Id");

                    b.HasIndex("PhoneCode_Id");

                    b.ToTable("people_phones", (string)null);
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Personal.Infrastructure.Entity.PersonalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<Guid?>("AirPortsEntityId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Airline_Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("airline_Id");

                    b.Property<Guid?>("AirlinesEntityId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Airport_Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("airport_Id");

                    b.Property<DateTime?>("Created_In")
                        .HasColumnType("date")
                        .HasColumnName("created_in");

                    b.Property<DateTime?>("Entry_Date")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<Guid?>("PeopleEntityId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("People_Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("people_Id");

                    b.Property<Guid?>("PersonalPositionsEntityId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Position_Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("position_Id");

                    b.Property<DateTime?>("Updated_In")
                        .HasColumnType("date")
                        .HasColumnName("updated_in");

                    b.HasKey("Id");

                    b.HasIndex("AirPortsEntityId");

                    b.HasIndex("Airline_Id");

                    b.HasIndex("AirlinesEntityId");

                    b.HasIndex("Airport_Id");

                    b.HasIndex("PeopleEntityId");

                    b.HasIndex("People_Id")
                        .IsUnique();

                    b.HasIndex("PersonalPositionsEntityId");

                    b.HasIndex("Position_Id");

                    b.ToTable("Personal", (string)null);
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.PersonalPositions.Infrastructure.Entity.PersonalPositionsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("personalpositions", (string)null);
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.PhoneCodes.Infrastructure.Entity.PhoneCodesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Country_Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("country_code");

                    b.Property<string>("Country_Name")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("country_name");

                    b.HasKey("Id");

                    b.HasIndex("Country_Code")
                        .IsUnique();

                    b.ToTable("people_code", (string)null);
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Rates.Infrastructure.Entity.RatesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<decimal>("Base_Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("base_price");

                    b.Property<Guid?>("CabinTypesEntityId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Cabin_Type_Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("cabin_type_id");

                    b.Property<Guid?>("PassengerTypesEntityId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Passenger_Type_Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("passenger_type_id");

                    b.Property<Guid>("Route_Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("route_id");

                    b.Property<Guid?>("RoutesEntityId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Season_Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("season_id");

                    b.Property<Guid?>("SeasonsEntityId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("Valid_From")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("Valid_To")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.HasKey("Id");

                    b.HasIndex("CabinTypesEntityId");

                    b.HasIndex("Cabin_Type_Id");

                    b.HasIndex("PassengerTypesEntityId");

                    b.HasIndex("Passenger_Type_Id");

                    b.HasIndex("RoutesEntityId");

                    b.HasIndex("Season_Id");

                    b.HasIndex("SeasonsEntityId");

                    b.HasIndex("Route_Id", "Cabin_Type_Id", "Passenger_Type_Id", "Season_Id")
                        .IsUnique();

                    b.ToTable("fares", null, t =>
                        {
                            t.HasCheckConstraint("CK_Fares_BasePrice", "base_price >= 0");

                            t.HasCheckConstraint("CK_Fares_Dates", "valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from");
                        });
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Regions.Infrastructure.Entity.RegionsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("Countries_id")
                        .HasColumnType("char(36)")
                        .HasColumnName("countries_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Countries_id");

                    b.ToTable("regions", (string)null);
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.RouteStopovers.Infrastructure.Entity.RouteStopoversEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid?>("AirPortsEntityId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Airport_Stop_Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("airport_stop_id");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("order");

                    b.Property<Guid>("Route_Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("route_id");

                    b.Property<Guid?>("RoutesEntityId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Stop_Duration_Min")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("stop_duration_min");

                    b.HasKey("Id");

                    b.HasIndex("AirPortsEntityId");

                    b.HasIndex("Airport_Stop_Id");

                    b.HasIndex("RoutesEntityId");

                    b.HasIndex("Route_Id", "Order")
                        .IsUnique();

                    b.ToTable("route_stops", (string)null);
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Routes.Infrastructure.Entity.RoutesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid?>("AirPortsEntityId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Airport_Destination_Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("airport_destination_id");

                    b.Property<Guid>("Airport_Origin_Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("airport_origin_id");

                    b.Property<int?>("Distance_km")
                        .HasColumnType("int")
                        .HasColumnName("distance_km");

                    b.Property<int?>("Estimated_Duration_Min")
                        .HasColumnType("int")
                        .HasColumnName("estimated_duration_Min");

                    b.HasKey("Id");

                    b.HasIndex("AirPortsEntityId");

                    b.HasIndex("Airport_Destination_Id");

                    b.HasIndex("Airport_Origin_Id", "Airport_Destination_Id")
                        .IsUnique();

                    b.ToTable("routes", (string)null);
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Seasons.Infrastructure.Entity.SeasonsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price_Factor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,4)")
                        .HasDefaultValue(1.0000m)
                        .HasColumnName("price_factor");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("seasons", null, t =>
                        {
                            t.HasCheckConstraint("CK_Seasons_PriceFactor", "price_factor > 0");
                        });
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.StaffAvailability.Infrastructure.Entity.StaffAvailabilityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("AvailabilityState_Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("availabilityState_id");

                    b.Property<DateTime?>("End_Date")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("observation");

                    b.Property<Guid>("People_Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("peoble_id");

                    b.Property<DateTime?>("Start_Date")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("AvailabilityState_Id");

                    b.HasIndex("People_Id");

                    b.ToTable("staff_availability", null, t =>
                        {
                            t.HasCheckConstraint("CK_StaffAvailability_Fechas", "end_date IS NULL OR end_date > start_date");
                        });
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.ViaTypes.Infrastructure.Entity.ViaTypesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("viatypes", (string)null);
                });

            modelBuilder.Entity("AirlinesEntity", b =>
                {
                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.Countries.Infrastructure.Entity.CountriesEntity", null)
                        .WithMany("Airlines")
                        .HasForeignKey("CountriesEntityId");

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.Countries.Infrastructure.Entity.CountriesEntity", "Countries")
                        .WithMany()
                        .HasForeignKey("Country_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Countries");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Addresses.Infrastructure.Entity.AddressesEntity", b =>
                {
                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.Cities.Infrastructure.Entity.CitiesEntity", null)
                        .WithMany("Addresses")
                        .HasForeignKey("CitiesEntityId");

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.Cities.Infrastructure.Entity.CitiesEntity", "Cities")
                        .WithMany()
                        .HasForeignKey("Cities_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.ViaTypes.Infrastructure.Entity.ViaTypesEntity", "ViaTypes")
                        .WithMany()
                        .HasForeignKey("ViaType_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.ViaTypes.Infrastructure.Entity.ViaTypesEntity", null)
                        .WithMany("Addresses")
                        .HasForeignKey("ViaTypesEntityId");

                    b.Navigation("Cities");

                    b.Navigation("ViaTypes");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.AirPorts.Infrastructure.Entity.AirPortsEntity", b =>
                {
                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.Cities.Infrastructure.Entity.CitiesEntity", null)
                        .WithMany("AirPorts")
                        .HasForeignKey("CitiesEntityId");

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.Cities.Infrastructure.Entity.CitiesEntity", "Cities")
                        .WithMany()
                        .HasForeignKey("Cities_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cities");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Aircraft.Infrastructure.Entity.AircraftEntity", b =>
                {
                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.AircraftModels.Infrastructure.Entity.AircraftModelsEntity", null)
                        .WithMany("Aircraft")
                        .HasForeignKey("AircraftModelsEntityId");

                    b.HasOne("AirlinesEntity", "Airlines")
                        .WithMany()
                        .HasForeignKey("Airline_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirlinesEntity", null)
                        .WithMany("Aircraft")
                        .HasForeignKey("AirlinesEntityId");

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.AircraftModels.Infrastructure.Entity.AircraftModelsEntity", "AircraftModels")
                        .WithMany()
                        .HasForeignKey("Models_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AircraftModels");

                    b.Navigation("Airlines");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.AircraftModels.Infrastructure.Entity.AircraftModelsEntity", b =>
                {
                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.AircraftManufacturers.Infrastructure.Entity.AircraftManufacturersEntity", null)
                        .WithMany("AircraftModels")
                        .HasForeignKey("AircraftManufacturersEntityId");

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.AircraftManufacturers.Infrastructure.Entity.AircraftManufacturersEntity", "AircraftManu")
                        .WithMany()
                        .HasForeignKey("Manufacturer_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AircraftManu");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.AirportAirline.Infrastructure.Entity.AirportAirlineEntity", b =>
                {
                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.AirPorts.Infrastructure.Entity.AirPortsEntity", null)
                        .WithMany("AirportAirline")
                        .HasForeignKey("AirPortsEntityId");

                    b.HasOne("AirlinesEntity", "Airlines")
                        .WithMany()
                        .HasForeignKey("Airline_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirlinesEntity", null)
                        .WithMany("AirportAirline")
                        .HasForeignKey("AirlinesEntityId");

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.AirPorts.Infrastructure.Entity.AirPortsEntity", "AirPorts")
                        .WithMany()
                        .HasForeignKey("Airport_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AirPorts");

                    b.Navigation("Airlines");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.CabinConfiguration.Infrastructure.Entity.CabinConfigurationEntity", b =>
                {
                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.Aircraft.Infrastructure.Entity.AircraftEntity", null)
                        .WithMany("CabinConfiguration")
                        .HasForeignKey("AircraftEntityId");

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.Aircraft.Infrastructure.Entity.AircraftEntity", "Aircraft")
                        .WithMany()
                        .HasForeignKey("Aircraft_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.CabinTypes.Infrastructure.Entity.CabinTypesEntity", "CabinTypes")
                        .WithMany()
                        .HasForeignKey("Cabin_Type_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aircraft");

                    b.Navigation("CabinTypes");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Cities.Infrastructure.Entity.CitiesEntity", b =>
                {
                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.Regions.Infrastructure.Entity.RegionsEntity", "Regions")
                        .WithMany("Cities")
                        .HasForeignKey("Regions_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Regions");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Countries.Infrastructure.Entity.CountriesEntity", b =>
                {
                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.Continents.Infrastructure.Entity.ContinentsEntity", "Continents")
                        .WithMany("Countries")
                        .HasForeignKey("Continents_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Continents");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Customers.Infrastructure.Entity.CustomersEntity", b =>
                {
                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.People.Infrastructure.Entity.PeopleEntity", "People")
                        .WithMany()
                        .HasForeignKey("People_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("People");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.FlightStatusTransitions.Infrastructure.Entity.FlightStatusTransitionsEntity", b =>
                {
                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.FlightStatus.Infrastructure.Entity.FlightStatusEntity", "DestinationState")
                        .WithMany()
                        .HasForeignKey("Destination_State_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.FlightStatus.Infrastructure.Entity.FlightStatusEntity", null)
                        .WithMany("FlightStatusTransitions")
                        .HasForeignKey("FlightStatusEntityId");

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.FlightStatus.Infrastructure.Entity.FlightStatusEntity", "OriginState")
                        .WithMany()
                        .HasForeignKey("Origin_State_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinationState");

                    b.Navigation("OriginState");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Flights.Infrastructure.Entity.FlightsEntity", b =>
                {
                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.Aircraft.Infrastructure.Entity.AircraftEntity", null)
                        .WithMany("Flights")
                        .HasForeignKey("AircraftEntityId");

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.Aircraft.Infrastructure.Entity.AircraftEntity", "Aircraft")
                        .WithMany()
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirlinesEntity", "Airline")
                        .WithMany()
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirlinesEntity", null)
                        .WithMany("Flights")
                        .HasForeignKey("AirlinesEntityId");

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.FlightStatus.Infrastructure.Entity.FlightStatusEntity", "FlightState")
                        .WithMany()
                        .HasForeignKey("FlightStateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.FlightStatus.Infrastructure.Entity.FlightStatusEntity", null)
                        .WithMany("Flights")
                        .HasForeignKey("FlightStatusEntityId");

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.Routes.Infrastructure.Entity.RoutesEntity", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aircraft");

                    b.Navigation("Airline");

                    b.Navigation("FlightState");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.People.Infrastructure.Entity.PeopleEntity", b =>
                {
                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.Addresses.Infrastructure.Entity.AddressesEntity", "Addresses")
                        .WithMany()
                        .HasForeignKey("Addresses_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.DocumentTypes.Infrastructure.Entity.DocumentTypesEntity", "DocumentTypes")
                        .WithMany()
                        .HasForeignKey("DocumentTypes_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Addresses");

                    b.Navigation("DocumentTypes");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.PeopleEmails.Infrastructure.Entity.PeopleEmailsEntity", b =>
                {
                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.EmailDomains.Infrastructure.Entity.EmailDomainsEntity", "EmailDomains")
                        .WithMany()
                        .HasForeignKey("Domain_Email_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.EmailDomains.Infrastructure.Entity.EmailDomainsEntity", null)
                        .WithMany("PeopleEmails")
                        .HasForeignKey("EmailDomainsEntityId");

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.People.Infrastructure.Entity.PeopleEntity", null)
                        .WithMany("PeopleEmails")
                        .HasForeignKey("PeopleEntityId");

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.People.Infrastructure.Entity.PeopleEntity", "People")
                        .WithMany()
                        .HasForeignKey("People_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmailDomains");

                    b.Navigation("People");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.PeoplePhones.Infrastructure.Entity.PeoplePhonesEntity", b =>
                {
                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.People.Infrastructure.Entity.PeopleEntity", null)
                        .WithMany("PeoplePhones")
                        .HasForeignKey("PeopleEntityId");

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.People.Infrastructure.Entity.PeopleEntity", "People")
                        .WithMany()
                        .HasForeignKey("People_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.PhoneCodes.Infrastructure.Entity.PhoneCodesEntity", "PhoneCodes")
                        .WithMany()
                        .HasForeignKey("PhoneCode_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("People");

                    b.Navigation("PhoneCodes");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Personal.Infrastructure.Entity.PersonalEntity", b =>
                {
                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.AirPorts.Infrastructure.Entity.AirPortsEntity", null)
                        .WithMany("Personal")
                        .HasForeignKey("AirPortsEntityId");

                    b.HasOne("AirlinesEntity", "Airlines")
                        .WithMany()
                        .HasForeignKey("Airline_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirlinesEntity", null)
                        .WithMany("Personal")
                        .HasForeignKey("AirlinesEntityId");

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.AirPorts.Infrastructure.Entity.AirPortsEntity", "AirPorts")
                        .WithMany()
                        .HasForeignKey("Airport_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.People.Infrastructure.Entity.PeopleEntity", null)
                        .WithMany("Personal")
                        .HasForeignKey("PeopleEntityId");

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.People.Infrastructure.Entity.PeopleEntity", "People")
                        .WithMany()
                        .HasForeignKey("People_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.PersonalPositions.Infrastructure.Entity.PersonalPositionsEntity", null)
                        .WithMany("Personal")
                        .HasForeignKey("PersonalPositionsEntityId");

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.PersonalPositions.Infrastructure.Entity.PersonalPositionsEntity", "PersonalPositions")
                        .WithMany()
                        .HasForeignKey("Position_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AirPorts");

                    b.Navigation("Airlines");

                    b.Navigation("People");

                    b.Navigation("PersonalPositions");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Rates.Infrastructure.Entity.RatesEntity", b =>
                {
                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.CabinTypes.Infrastructure.Entity.CabinTypesEntity", null)
                        .WithMany("Rates")
                        .HasForeignKey("CabinTypesEntityId");

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.CabinTypes.Infrastructure.Entity.CabinTypesEntity", "CabinType")
                        .WithMany()
                        .HasForeignKey("Cabin_Type_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.PassengerTypes.Infrastructure.Entity.PassengerTypesEntity", null)
                        .WithMany("Rates")
                        .HasForeignKey("PassengerTypesEntityId");

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.PassengerTypes.Infrastructure.Entity.PassengerTypesEntity", "PassengerType")
                        .WithMany()
                        .HasForeignKey("Passenger_Type_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.Routes.Infrastructure.Entity.RoutesEntity", "Route")
                        .WithMany()
                        .HasForeignKey("Route_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.Routes.Infrastructure.Entity.RoutesEntity", null)
                        .WithMany("Rates")
                        .HasForeignKey("RoutesEntityId");

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.Seasons.Infrastructure.Entity.SeasonsEntity", "Season")
                        .WithMany()
                        .HasForeignKey("Season_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.Seasons.Infrastructure.Entity.SeasonsEntity", null)
                        .WithMany("Rates")
                        .HasForeignKey("SeasonsEntityId");

                    b.Navigation("CabinType");

                    b.Navigation("PassengerType");

                    b.Navigation("Route");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Regions.Infrastructure.Entity.RegionsEntity", b =>
                {
                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.Countries.Infrastructure.Entity.CountriesEntity", "Countries")
                        .WithMany("Regions")
                        .HasForeignKey("Countries_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Countries");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.RouteStopovers.Infrastructure.Entity.RouteStopoversEntity", b =>
                {
                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.AirPorts.Infrastructure.Entity.AirPortsEntity", null)
                        .WithMany("RouteStopovers")
                        .HasForeignKey("AirPortsEntityId");

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.AirPorts.Infrastructure.Entity.AirPortsEntity", "Airport")
                        .WithMany()
                        .HasForeignKey("Airport_Stop_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.Routes.Infrastructure.Entity.RoutesEntity", "Route")
                        .WithMany()
                        .HasForeignKey("Route_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.Routes.Infrastructure.Entity.RoutesEntity", null)
                        .WithMany("RouteStopovers")
                        .HasForeignKey("RoutesEntityId");

                    b.Navigation("Airport");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Routes.Infrastructure.Entity.RoutesEntity", b =>
                {
                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.AirPorts.Infrastructure.Entity.AirPortsEntity", null)
                        .WithMany("Routes")
                        .HasForeignKey("AirPortsEntityId");

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.AirPorts.Infrastructure.Entity.AirPortsEntity", "AirportDestination")
                        .WithMany()
                        .HasForeignKey("Airport_Destination_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.AirPorts.Infrastructure.Entity.AirPortsEntity", "AirportOrigin")
                        .WithMany()
                        .HasForeignKey("Airport_Origin_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AirportDestination");

                    b.Navigation("AirportOrigin");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.StaffAvailability.Infrastructure.Entity.StaffAvailabilityEntity", b =>
                {
                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.AvailabilityStates.Infrastructure.Entity.AvailabilityStatesEntity", "AvailabilityStates")
                        .WithMany()
                        .HasForeignKey("AvailabilityState_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestorDeVuelosProyectoFinal.src.Moduls.People.Infrastructure.Entity.PeopleEntity", "People")
                        .WithMany()
                        .HasForeignKey("People_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AvailabilityStates");

                    b.Navigation("People");
                });

            modelBuilder.Entity("AirlinesEntity", b =>
                {
                    b.Navigation("Aircraft");

                    b.Navigation("AirportAirline");

                    b.Navigation("Flights");

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.AirPorts.Infrastructure.Entity.AirPortsEntity", b =>
                {
                    b.Navigation("AirportAirline");

                    b.Navigation("Personal");

                    b.Navigation("RouteStopovers");

                    b.Navigation("Routes");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Aircraft.Infrastructure.Entity.AircraftEntity", b =>
                {
                    b.Navigation("CabinConfiguration");

                    b.Navigation("Flights");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.AircraftManufacturers.Infrastructure.Entity.AircraftManufacturersEntity", b =>
                {
                    b.Navigation("AircraftModels");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.AircraftModels.Infrastructure.Entity.AircraftModelsEntity", b =>
                {
                    b.Navigation("Aircraft");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.CabinTypes.Infrastructure.Entity.CabinTypesEntity", b =>
                {
                    b.Navigation("Rates");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Cities.Infrastructure.Entity.CitiesEntity", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("AirPorts");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Continents.Infrastructure.Entity.ContinentsEntity", b =>
                {
                    b.Navigation("Countries");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Countries.Infrastructure.Entity.CountriesEntity", b =>
                {
                    b.Navigation("Airlines");

                    b.Navigation("Regions");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.EmailDomains.Infrastructure.Entity.EmailDomainsEntity", b =>
                {
                    b.Navigation("PeopleEmails");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.FlightStatus.Infrastructure.Entity.FlightStatusEntity", b =>
                {
                    b.Navigation("FlightStatusTransitions");

                    b.Navigation("Flights");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.PassengerTypes.Infrastructure.Entity.PassengerTypesEntity", b =>
                {
                    b.Navigation("Rates");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.People.Infrastructure.Entity.PeopleEntity", b =>
                {
                    b.Navigation("PeopleEmails");

                    b.Navigation("PeoplePhones");

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.PersonalPositions.Infrastructure.Entity.PersonalPositionsEntity", b =>
                {
                    b.Navigation("Personal");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Regions.Infrastructure.Entity.RegionsEntity", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Routes.Infrastructure.Entity.RoutesEntity", b =>
                {
                    b.Navigation("Rates");

                    b.Navigation("RouteStopovers");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.Seasons.Infrastructure.Entity.SeasonsEntity", b =>
                {
                    b.Navigation("Rates");
                });

            modelBuilder.Entity("GestorDeVuelosProyectoFinal.src.Moduls.ViaTypes.Infrastructure.Entity.ViaTypesEntity", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
